-- AlterTable
ALTER TABLE "Contract" ADD COLUMN "signPageNumber" INTEGER;
ALTER TABLE "Contract" ADD COLUMN "signX" DOUBLE PRECISION;
ALTER TABLE "Contract" ADD COLUMN "signY" DOUBLE PRECISION;
ALTER TABLE "Contract" ADD COLUMN "signWidth" DOUBLE PRECISION;
ALTER TABLE "Contract" ADD COLUMN "signHeight" DOUBLE PRECISION;
